version: '3'

services:
  practical_microservices_db:
    image: postgres:10.3
    environment:
      - POSTGRES_DB=practical_microservices
      - POSTGRES_PASSWORD=example
    ports:
      - '0.0.0.0:5431:5432'
